release:
    github:
        owner: Parisa68
        name: FEGA-Norway

builds:
    - goos:
          - darwin
      goarch:
          - amd64
      goarm:
          - "6"
  
archives:
    - name_template: >-
          {{- .Binary }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end -}}

#  -
#    replacements:
#      amd64: x86_64
#      386: i386
#
#    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
