name: Build Changed Components

on:
  push:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect path changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            lega-commander:
              - 'cli/lega-commander/**'
            e2eTests:
              - 'e2eTests/**'
            clearinghouse:
              - 'lib/clearinghouse/**'
            crypt4gh:
              - 'lib/crypt4gh/**'
            tsd-file-api-client:
              - 'lib/tsd-file-api-client/**'
            cega-mock:
              - 'services/cega-mock/**'
            localega-tsd-proxy:
              - 'services/localega-tsd-proxy/**'
            mq-interceptor:
              - 'services/mq-interceptor/**'
            tsd-api-mock:
              - 'services/tsd-api-mock/**'

      - name: Set matrix based on changes
        id: set-matrix
        run: |
          components=()
          if [[ "${{ steps.changes.outputs.lega-commander }}" == "true" ]]; then components+=('"lega-commander"'); fi
          if [[ "${{ steps.changes.outputs.e2eTests }}" == "true" ]]; then components+=('"e2eTests"'); fi
          if [[ "${{ steps.changes.outputs.clearinghouse }}" == "true" ]]; then components+=('"clearinghouse"'); fi
          if [[ "${{ steps.changes.outputs.crypt4gh }}" == "true" ]]; then components+=('"crypt4gh"'); fi
          if [[ "${{ steps.changes.outputs.tsd-file-api-client }}" == "true" ]]; then components+=('"tsd-file-api-client"'); fi
          if [[ "${{ steps.changes.outputs.cega-mock }}" == "true" ]]; then components+=('"cega-mock"'); fi
          if [[ "${{ steps.changes.outputs.localega-tsd-proxy }}" == "true" ]]; then components+=('"localega-tsd-proxy"'); fi
          if [[ "${{ steps.changes.outputs.mq-interceptor }}" == "true" ]]; then components+=('"mq-interceptor"'); fi
          if [[ "${{ steps.changes.outputs.tsd-api-mock }}" == "true" ]]; then components+=('"tsd-api-mock"'); fi

          json=$(jq -n --argjson arr "[${components[*]}]" '$arr')
          echo "matrix=$json" >> $GITHUB_OUTPUT
        shell: bash

  build:
    needs: detect-changes
    if: ${{ fromJson(needs.detect-changes.outputs.matrix) != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: print
        run: echo "${{ matrix.component }}"
