name: NEW Release

on:
  push:

jobs:
  detect:
    uses: ./.github/workflows/chenge-detection.yml

  build:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.detect.outputs.matrix).component != '' && fromJson(needs.detect.outputs.matrix).component != null && fromJson(needs.detect.outputs.matrix).component | length > 0 }}
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect.outputs.changed-components).component }}
    steps:
      - name: Check if array is empty
        run: |
          echo "Component array: ${{ toJson(fromJson(needs.detect.outputs.changed-components).component) }}"
          echo "Is empty array: ${{ fromJson(needs.detect.outputs.changed-components).component == '[]' }}"
          echo "Array equals empty: ${{ toJson(fromJson(needs.detect.outputs.changed-components).component) == '[]' }}"
      - name: Print 
        run: echo "${{ matrix.component }}"
