name: NEW Release

on:
  push:

jobs:
  detect:
    uses: ./.github/workflows/chenge-detection.yml

  build:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.detect.outputs.matrix).component != [] }}
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect.outputs.changed-components).component }}
    steps:
      - name: Print 
        run: echo "${{ matrix.component }}"
