name: Fetch New Version

on:
  workflow_call:
    inputs:
      component_name:
        description: "The name of the component"
        required: true
        type: string
    outputs:
      new_version:
        description: "The new incremented version for the component"
        value: ${{ jobs.get-latest-tag.outputs.new_version }}


jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_output.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Give a new tag for the component
        id: get_tag
        run: |
          component_name="${{ inputs.component_name }}"
          
          latest_tag=$(git tag --list "$component_name-*" | sort -V | tail -n 1)

          if [ -z "$latest_tag" ]; then
            new_version="0.0.1"
          else
            version_part=${latest_tag#"$component_name-"}
            IFS='.' read -r major minor patch <<< "$version_part"
            commits=$(git log "$latest_tag"..HEAD --no-merges --pretty=format:"%h %s")
            echo "$commits"
            if echo "$commits" | grep -q "#major"; then
              new_version="$((major + 1)).0.0"
            elif echo "$commits" | grep -q "#minor"; then
              new_version="$major.$((minor + 1)).0"
            else
              new_version="$major.$minor.$((patch + 1))"
            fi
          fi
          
          echo "Latest tag for $component_name: $latest_tag"
          echo "New version for $component_name: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Set output for the reusable workflow
        id: set_output
        run: echo "new_version=${{ env.new_version }}" >> $GITHUB_OUTPUT
