# Fake change to test the action
name: Publish
on:
  push:

permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  publish-mq-interceptor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Get current version for mq-interceptor
        id: version_mq_interceptor
        run: |
          MQ_INTERCEPTOR_VERSION=$(grep -oP 'version = "\K[0-9]+\.[0-9]+\.[0-9]+' services/mq-interceptor/build.gradle.kts)
          echo "mq_interceptor_version=$MQ_INTERCEPTOR_VERSION" >> $GITHUB_OUTPUT
      - name: Bump patch version for mq-interceptor
        id: bump_mq_interceptor_version
        run: |
          MQ_INTERCEPTOR_VERSION="${{ steps.version_mq_interceptor.outputs.mq_interceptor_version }}"
          VERSION_PARTS=(${MQ_INTERCEPTOR_VERSION//./ })
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          NEW_MQ_INTERCEPTOR_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new_mq_interceptor_version=$NEW_MQ_INTERCEPTOR_VERSION" >> $GITHUB_OUTPUT
      - name: Update version in mq-interceptor's build.gradle.kts
        run: sed -i "s#version = \".*\"#version = \"${{ steps.bump_mq_interceptor_version.outputs.new_mq_interceptor_version }}\"#" services/mq-interceptor/build.gradle.kts
      - name: Set Repository Name
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./services/mq-interceptor
          push: true
          no-cache: 'true'
          tags: |
            ghcr.io/${{ env.repo_name }}:mq-interceptor-${{ steps.bump_mq_interceptor_version.outputs.new_mq_interceptor_version }}
            ghcr.io/${{ env.repo_name }}:mq-interceptor-latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            org.opencontainers.image.revision=${{ github.sha }}
#      - name: Commit and Push Changes
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          BRANCH_NAME=main
#          git config user.name 'GitHub Actions'
#          git config user.email 'actions@github.com'
#          git config pull.rebase false
#          for i in {1..3}; do
#            git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/ELIXIR-NO/FEGA-Norway.git $BRANCH_NAME
#            git add -A
#            git commit -m "bump mq-interceptor version to ${{ steps.bump_mq_interceptor_version.outputs.new_mq_interceptor_version }}"
#            if git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ELIXIR-NO/FEGA-Norway.git HEAD:refs/heads/$BRANCH_NAME; then
#              break
#            else
#              echo "Push failed, retrying in 5 seconds..."
#              sleep 5
#            fi
#          done

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ghcr.io/${{ env.repo_name }}:mq-interceptor-${{ steps.bump_mq_interceptor_version.outputs.new_mq_interceptor_version }}
          format: 'sarif'
          exit-code: '1'
          ignore-unfixed: true
          output: 'mq-interceptor-result.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'mq-interceptor-result.sarif'
          category: 'mq-interceptor'

