name: PR Merged

on:
  pull_request:
    types:
      - closed

jobs:
  hello_world:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
